// Generates src/generated/build-info.ts with the current git short hash.
// Wired into package.json as `predev` and `prebuild` so every dev run and
// every build produces a fresh stamp without modifying tracked files.
//
// The generated file is gitignored. Outside a git checkout (e.g. inside a
// published npm tarball) the hash falls back to "tarball" so consumers can
// still tell the engine_version isn't a built-from-git artifact.

import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT = resolve(HERE, '../src/generated/build-info.ts');

let hash;
try {
  hash = execSync('git rev-parse --short HEAD', { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
} catch {
  hash = 'tarball';
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT,
  '// Generated by scripts/stamp-version.mjs. Do not edit by hand.\n' +
  `export const ENGINE_GIT_HASH = '${hash}';\n`
);
console.error(`stamp-version: ENGINE_GIT_HASH = ${hash}`);
